# --------------------- phishscope_part0 ---------------------
phishscope_part0:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: phishscope_part0
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.2,0.005,0.5
  gpu: 0
  hidden_dim: 512
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.2,0.005,0.5
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 8
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: true
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- phishscope_part1 ---------------------
phishscope_part1:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: phishscope_part1
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.2,0.005,0.5
  gpu: 0
  hidden_dim: 512
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.2,0.005,0.5
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 8
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: true
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- phishscope_part2 ---------------------
phishscope_part2:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: phishscope_part2
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.2,0.005,0.5
  gpu: 0
  hidden_dim: 512
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.2,0.005,0.5
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 8
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: true
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- phishscope_part3 ---------------------
phishscope_part3:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: phishscope_part3
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.2,0.005,0.5
  gpu: 0
  hidden_dim: 512
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.2,0.005,0.5
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 8
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: true
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true

# --------------------- phishscope_part4 ---------------------
phishscope_part4:
  activation: prelu
  alpha_l: 3
  attn_drop: 0
  dataset: phishscope_part4
  decoder: han
  encoder: han
  eva_lr: 0.01
  eva_wd: 0
  feat_drop: 0.4
  feat_mask_rate: 0.2,0.005,0.5
  gpu: 0
  hidden_dim: 512
  l2_coef: 0
  leave_unchanged: 0.1
  loss_fn: sce
  lr: 0.001
  mae_epochs: 10000
  mask_rate: 0.2,0.005,0.5
  mp2vec_feat_alpha_l: 2
  mp2vec_feat_drop: 0.2
  mp2vec_feat_pred_loss_weight: 0.5
  mp_edge_alpha_l: 3
  mp_edge_mask_rate: 0.5
  mp_edge_recon_loss_weight: 0.5
  mps_batch_size: 256
  mps_context_size: 5
  mps_embedding_dim: 64
  mps_epoch: 20
  mps_lr: 0.005
  mps_num_negative_samples: 3
  mps_walk_length: 10
  mps_walks_per_node: 3
  n_labels: 2
  negative_slope: 0.2
  nei_num: 2
  norm: batchnorm
  num_heads: 8
  num_layers: 2
  num_out_heads: 1
  optimizer: adam
  patience: 10
  replace_rate: 0.3
  residual: true
  scheduler: true
  scheduler_gamma: 0.99
  use_mp2vec_feat_pred: true
  use_mp_edge_recon: true